# Generated by Django 4.2.24 on 2025-09-11 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tom_targets', '0029_alter_basetarget_permissions'),
        ('custom_code', '0012_merge_0010_timeused_0011_nedlvscatalog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SNExTarget',
            fields=[
                ('basetarget_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tom_targets.basetarget')),
                ('redshift', models.FloatField(default=0)),
                ('classification', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('tweet', models.BooleanField(default=False)),
                ('reference', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('observing_run_priority', models.FloatField(default=0)),
                ('last_nondetection', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('first_detection', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('maximum', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('target_description', models.CharField(blank=True, default='', max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'target',
                'permissions': (('view_target', 'View Target'), ('add_target', 'Add Target'), ('change_target', 'Change Target'), ('delete_target', 'Delete Target')),
            },
            bases=('tom_targets.basetarget',),
        ),
        migrations.AlterField(
            model_name='interestedpersons',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_code.snextarget'),
        ),
        migrations.AlterField(
            model_name='papers',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_code.snextarget'),
        ),
        migrations.AlterField(
            model_name='reduceddatumextra',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_code.snextarget'),
        ),
        migrations.AlterField(
            model_name='targettags',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_code.snextarget'),
        ),
    ]
