# Generated by Django 4.2.25 on 2025-11-26 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_code', '0013_snextarget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snextarget',
            name='redshift',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
