# Generated by Django 5.2.12 on 2026-03-19 23:10

from django.db import migrations, models
from django.db.models import F

def populate_pipeline_id(apps, schema_editor):
    SNExTarget = apps.get_model('custom_code', 'SNExTarget')
    SNExTarget.objects.filter(pipeline_id__isnull=True).update(pipeline_id=F('id'))


class Migration(migrations.Migration):

    dependencies = [
        ('custom_code', '0015_userregistrationinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='snextarget',
            name='pipeline_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='snextarget',
            name='observing_run_priority',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.RunPython(populate_pipeline_id, migrations.RunPython.noop),
    ]
