# Generated by Django 5.2.12 on 2026-03-20 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_code', '0016_snextarget_pipeline_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interestedpersons',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_code.snextarget'),
        ),
        migrations.AlterField(
            model_name='papers',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_code.snextarget'),
        ),
        migrations.AlterField(
            model_name='reduceddatumextra',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_code.snextarget'),
        ),
        migrations.AlterField(
            model_name='targettags',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_code.snextarget'),
        ),
    ]
