# Generated by Django 5.2.12 on 2026-03-20 17:21

from django.db import migrations, models
import json

def convert_to_json(apps, schema_editor):
    ReducedDatumExtra = apps.get_model('custom_code', 'ReducedDatumExtra')
    for rde in ReducedDatumExtra.objects.all():
        if isinstance(rde.value, str):
            try:
                # Try valid JSON first
                json.loads(rde.value)
            except (json.JSONDecodeError, TypeError):
                try:
                    # Convert Python dict string to valid JSON
                    import ast
                    rde.value = json.dumps(ast.literal_eval(rde.value))
                    rde.save()
                except Exception as e:
                    print(f"Could not convert value for id {rde.id}: {rde.value} — {e}")


class Migration(migrations.Migration):

    dependencies = [
        ('custom_code', '0017_alter_interestedpersons_target_alter_papers_target_and_more'),
    ]

    operations = [
        migrations.RunPython(convert_to_json, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='reduceddatumextra',
            name='value',
            field=models.JSONField(blank=True, default=dict, help_text='String value of the information being stored', verbose_name='Value'),
        )
    ]
