# Generated by Django 5.2.12 on 2026-03-20 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_code', '0017_alter_interestedpersons_target_alter_papers_target_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reduceddatumextra',
            name='value',
            field=models.JSONField(blank=True, default='', help_text='String value of the information being stored', verbose_name='Value'),
        ),
    ]
