# Generated by Django 5.2.12 on 2026-03-20 00:42
import json
import django.db.models.deletion
from django.db import migrations, models


def populate_reduced_datum(apps, schema_editor):
    ReducedDatumExtra = apps.get_model('custom_code', 'ReducedDatumExtra')
    ReducedDatum = apps.get_model('tom_dataproducts', 'ReducedDatum')

    for rdextra in ReducedDatumExtra.objects.filter(key='snex_id'):
        try:
            value = json.loads(rdextra.value)
            rd_pk = value.get('snex2_id', '')
            snex_id = value.get('snex_id', '')
            if not rd_pk or not snex_id:
                continue

            rd = ReducedDatum.objects.get(pk=rd_pk)
            rdextra.reduced_datum = rd
            rdextra.save()

            rdextra_extras = ReducedDatumExtra.objects.filter(
                key='spec_extras',
                value__icontains=f'"snex_id": {snex_id}'
            ).first()
            if rdextra_extras:
                rdextra_extras.reduced_datum = rd
                rdextra_extras.save()
        except Exception as e:
            print(f'Failed to populate reduced_datum for ReducedDatumExtra {rdextra.pk}: {e}')


class Migration(migrations.Migration):
    dependencies = [
        ('custom_code', '0017_alter_interestedpersons_target_alter_papers_target_and_more'),
        ('tom_dataproducts', '0014_alter_reduceddatum_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='reduceddatumextra',
            name='reduced_datum',
            field=models.ForeignKey(default=1, help_text='ReducedDatum this extra belongs to', on_delete=django.db.models.deletion.CASCADE, to='tom_dataproducts.reduceddatum', verbose_name='ReducedDatum'),
            preserve_default=False,
        ),
        migrations.RunPython(populate_reduced_datum, migrations.RunPython.noop),
    ]