# Generated by Django 5.2.12 on 2026-03-20 17:21

import django.db.models.deletion
from django.db import migrations, models

def populate_reduced_datum_extras(apps, schema_editor):
    ReducedDatumExtra = apps.get_model('custom_code', 'ReducedDatumExtra')
    ReducedDatum = apps.get_model('tom_dataproducts', 'ReducedDatum')
    DataProduct = apps.get_model('tom_dataproducts', 'DataProduct')

    for rdextra in ReducedDatumExtra.objects.filter(value__data_product_id='"data_product_id":'):
        try:
            value = rdextra.value
            dp_pk = value.get('data_product_id', '')
            if not dp_pk:
                continue
            data_product = DataProduct.objects.get(pk=dp_pk)
            rdextra.data_product = data_product
            rdextra.save()
        except Exception as e:
            print(f'Failed to populate data_product for ReducedDatumExtra {rdextra.pk}: {e}')

    for rdextra in ReducedDatumExtra.objects.filter(key='snex_id'):
        try:
            value = rdextra.value
            rd_pk = value.get('snex2_id', '')
            snex_id = value.get('snex_id', '')
            if not rd_pk or not snex_id:
                continue
            try:
                rd = ReducedDatum.objects.get(pk=rd_pk)
            except ReducedDatum.DoesNotExist:
                rdextra.delete()

            rdextra_extras = ReducedDatumExtra.objects.filter(
                key='spec_extras',
                value__snex_id=snex_id
            ).first()
            if rdextra_extras:
                rdextra_extras.data_product = rd.data_product
                rdextra_extras.save()
        except Exception as e:
            print(f'Failed to populate reduced_datum for ReducedDatumExtra {rdextra.pk}: {e}')


class Migration(migrations.Migration):

    dependencies = [
        ('custom_code', '0018_alter_reduceddatumextra_value'),
        ('tom_dataproducts', '0014_alter_reduceddatum_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='reduceddatumextra',
            name='data_product',
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='tom_dataproducts.dataproduct',
                verbose_name='DataProduct',
                help_text='DataProduct this extra belongs to'
            ),
        ),
        migrations.RunPython(populate_reduced_datum_extras, migrations.RunPython.noop),
    ]
