# Generated by Django 5.2.12 on 2026-03-21 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_code', '0019_reduceddatumextra_data_product'),
        ('tom_dataproducts', '0014_alter_reduceddatum_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reduceddatumextra',
            name='data_product',
            field=models.ForeignKey(help_text='DataProduct this extra belongs to', on_delete=django.db.models.deletion.CASCADE, to='tom_dataproducts.dataproduct', verbose_name='DataProduct'),
        ),
    ]
