# Generated by Django 5.2.12 on 2026-04-21 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_code', '0020_alter_reduceddatumextra_data_product'),
    ]

    operations = [
        migrations.RenameModel('ReducedDatumExtra', 'DataProductExtra'),
        migrations.AddField(
            model_name='DataProductExtra',
            name='viewed',
            field=models.BooleanField(default=True, verbose_name='Boolean Value', help_text='Show in FLOYDS inbox')
            )
]