# Generated by Django 5.2.12 on 2026-04-21 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_code', '0021_auto_20260421_2154'),
        ('tom_dataproducts', '0014_alter_reduceddatum_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReducedDatumSpecExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reducer', models.CharField(default='', help_text='Who reduced this data', max_length=50, verbose_name='Reduced By')),
                ('show', models.BooleanField(default=True, help_text='Boolean for showing data on target page', verbose_name='Boolean')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('data_product', models.ForeignKey(help_text='DataProduct this extra belongs to', on_delete=django.db.models.deletion.CASCADE, to='tom_dataproducts.dataproduct', verbose_name='DataProduct')),
                ('reduced_datum', models.ForeignKey(help_text='ReducedDatum this extra belongs to', on_delete=django.db.models.deletion.CASCADE, to='tom_dataproducts.reduceddatum', verbose_name='ReducedDatum')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_code.snextarget')),
            ],
        ),
    ]