# Generated by Django 5.2.13 on 2026-04-30 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_code', '0022_reduceddatumextra'),
        ('tom_dataproducts', '0014_alter_reduceddatum_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataproductextra',
            name='data_type',
        ),
        migrations.RemoveField(
            model_name='dataproductextra',
            name='target',
        ),
        migrations.RemoveField(
            model_name='reduceddatumspecextra',
            name='data_product',
        ),
        migrations.RemoveField(
            model_name='reduceddatumspecextra',
            name='target',
        ),
        migrations.AddField(
            model_name='reduceddatumspecextra',
            name='version',
            field=models.CharField(blank=True, help_text='md5 hash', null=True, verbose_name='String'),
        ),
        migrations.AlterField(
            model_name='dataproductextra',
            name='data_product',
            field=models.OneToOneField(help_text='DataProduct this extra belongs to', on_delete=django.db.models.deletion.CASCADE, to='tom_dataproducts.dataproduct', verbose_name='DataProduct'),
        ),
        migrations.AlterField(
            model_name='reduceddatumspecextra',
            name='reduced_datum',
            field=models.OneToOneField(help_text='ReducedDatum this extra belongs to', on_delete=django.db.models.deletion.CASCADE, to='tom_dataproducts.reduceddatum', verbose_name='ReducedDatum'),
        ),
    ]